spring.application.name=sosmed
server.port=8088

# Enable hidden method filter untuk PATCH, PUT, DELETE
spring.mvc.hiddenmethod.filter.enabled=true

# Virtual thread
spring.threads.virtual.enabled=true

# --- KONFIGURASI DATABASE POKOK ---
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# --- KOLEKSI POOL HIKARI ---
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# --- STRATEGI PEMBUATAN TABEL ---
spring.sql.init.mode=always

## Config log aplikasi ##
logging.config=classpath:logback-spring.xml

# Secret Key JWT
secret-key=
expiration-jwt=86400000

# log spring sevurity
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# Cloudinary Configuration
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=

# Dokumentasi API
scalar.openapi.url=/v3/api-docs